### ISSUE TITLE
support for my{some_method}

### ISSUE THREAD

**Issue by kbaum** [rzane/baby_squeel#14]
Trying to drop in baby_squeel as a replacement for squeel to a large rails project but we make extensive use of the my{some_method} where some_method is a method in the class where we are building the query.  Is there an equivalent for that within baby_squeel?

thx!

**Comment by rzane** [comment]
I just added this with #15. However, I really do recommend providing arity to DSL blocks instead of using `my`. By doing so, your code will be a lot easier to debug when you do have an issue.

```ruby
Model.where.has { |t| t.title == 'Notice the use of the block parameter' }
```

This method is only available when using BabySqueel's compatibility mode, which monkey patches Active Record.

**Comment by kbaum** [comment]
I like that syntax too. It's just tough to test out this library as a
replacement for squeel on a large project without it being compatible to
begin with.

Just to clarify, what is the value of t in your example? In the readme, it
seems like it would be an instance of Model, but that is not the same
behavior as the my method from squeel.

Thanks for your help!

**Comment by kbaum** [comment]
Addressed https://github.com/rzane/baby_squeel/pull/15

**Comment by rzane** [comment]
In my example, `t` is an instance of `BabySqueel::DSL`, not an instance of `Model`. I believe Squeel works exactly the same way.
